name: GuildHome
version: ${project.version}
main: com.github.bryanser.guildhome.bukkit.BukkitMain
depend: [BrAPI,ProtocolLib]
softdepend:
    - PlaceholderAPI
    - WeLore
commands:
    GuildHome:
        aliases: [gh]
        usage: |
            §6/<command> >> §a打开公会菜单
            §6/<command> create 公会名 >> §a创建公会(需要支付50000节操)
            §6/<command> apply 公会名 >> §a申请加入公会
            §6/<command> inv 玩家名 >> §a邀请该玩家加入你所在的公会
            §d/<command> disband >> §c解散你的公会[只有会长可用,慎用,解散不能还原]